Issue/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.Issue_Main.as_view(), name='Industry_Analysis'),
    url(r'samsung', views.Issue_Samsung.as_view(), name='Industry_Analysis_samsung'),
    
    url(r'^all/', views.Issue_Main.as_view(), name='All'),
    url(r'^page/(?P<pk>\d+)/', views.Issue_detail.as_view(), name='detail'),
    url(r'^Industry_more/(?P<pk>\d+)/', views.Issue_Analysis_more.as_view(), name='more'),

    url(r'^Consumer/Apparel', views.Issue_Apparel.as_view(), name='Apparel'),
    url(r'^Consumer/Auto', views.Issue_Auto.as_view(), name='Auto'),
    url(r'^Consumer/Cosmetics', views.Issue_Cosmetics.as_view(), name='Cosmetics'),
    url(r'^Consumer/Distribution', views.Issue_Distribution.as_view(), name='Distribution'),
    url(r'^Consumer/Etertainment', views.Issue_Entertainment.as_view(), name='Entertainment'),
    url(r'^Consumer/Education_Service', views.Issue_Education_Service.as_view(), name='Education_Service'),
    url(r'^Consumer/Food_Beverage', views.Issue_Food_Beverage.as_view(), name='Food_Beverage'),
    url(r'^Consumer/Game', views.Issue_Game.as_view(), name='Game'),
    url(r'^Consumer/Media', views.Issue_Media.as_view(), name='Media'),
    url(r'^Consumer/', views.Issue_Consumer.as_view(), name='Consumer'),

    url(r'^Energy/Oil_Gas', views.Issue_Oil_Gas.as_view(), name='Oil&Gas'),
    url(r'^Energy/Petrochem', views.Issue_Petrochem.as_view(), name='Petrochem'),
    url(r'^Energy/Solar', views.Issue_Solar.as_view(), name='Solar'),
    url(r'^Energy/Utilities', views.Issue_Utilities.as_view(), name='Utilities'),
    url(r'^Energy/', views.Issue_Energy.as_view(), name='Energy'),

    url(r'^Financial/Bank', views.Issue_Bank.as_view(), name='Bank'),
    url(r'^Financial/Insurance', views.Issue_Insurance.as_view(), name='Insurance'),
    url(r'^Financial/Securities', views.Issue_Securities.as_view(), name='Securities'),
    url(r'^Financial/Other_Financial_Service', views.Issue_Other_Financial_Service.as_view(), name='Other_Financial_Service'),
    url(r'^Financial/', views.Issue_Financial.as_view(), name='Financial'),

    url(r'^Healthcare/Medical_equipment', views.Issue_Medical_equipment.as_view(), name='Medical_equipment'),
    url(r'^Healthcare/Pharmaceuticals', views.Issue_Pharmaceuticals.as_view(), name='Pharmaceuticals'),
    url(r'^Healthcare/Biotech', views.Issue_Biotech.as_view(), name='Biotech'),
    url(r'^Healthcare/', views.Issue_Healthcare.as_view(), name='Healthcare'),

    url(r'^Idustrials/Plant', views.Issue_Plant.as_view(), name='Plant'),
    url(r'^Idustrials/Shipbuilding', views.Issue_Shipbuilding.as_view(), name='Shipbuilding'),
    url(r'^Idustrials/', views.Issue_Idustrials.as_view(), name='Idustrials'),

    url(r'^Materials/Construction', views.Issue_Construction.as_view(), name='Construction'),
    url(r'^Materials/Steel', views.Issue_Steel.as_view(), name='Steel'),
    url(r'^Materials/Chemical', views.Issue_Chemical.as_view(), name='Chemical'),
    url(r'^Materials/', views.Issue_Materials.as_view(), name='Materials'),


    url(r'^Other/Conglomerates_Holdco', views.Issue_Conglomerates_Holdco.as_view(), name='Conglomerates_Holdco'),
    url(r'^Other/Trading', views.Issue_Trading.as_view(), name='Trading'),
    url(r'^Other/Other_other', views.Issue_Other_other.as_view(), name='Other_other'),
    url(r'^Other/', views.Issue_Other.as_view(), name='Other'),

    url(r'^Tech/E_commerce', views.Issue_E_commerce.as_view(), name='E_commerce'),
    url(r'^Tech/IT', views.Issue_IT.as_view(), name='IT'),
    url(r'^Tech/Machinery', views.Issue_Machinery.as_view(), name='Machinery'),
    url(r'^Tech/Semiconductor', views.Issue_Semiconductor.as_view(), name='Semiconductor'),
    url(r'^Tech/Display', views.Issue_Display.as_view(), name='Display'),
    url(r'^Tech/Internet_Service', views.Issue_Internet_Service.as_view(), name='Internet_Service'),
    url(r'^Tech/Software', views.Issue_Software.as_view(), name='Software'),
    url(r'^Tech/Tech_other', views.Issue_Tech_other.as_view(), name='Tech_other'),
    url(r'^Tech/', views.Issue_Tech.as_view(), name='Tech'),

    url(r'^Telecom/Telecom_Service', views.Issue_Telecom_Service.as_view(), name='Telecom_Service'),
    url(r'^Telecom/Telecom_Equipment', views.Issue_Telecom_Equipment.as_view(), name='Telecom_Equipment'),
    url(r'^Telecom', views.Issue_Telecom.as_view(), name='Telecom'),
]

#정규표현식에 따라서 홈페이지의 url을 만들어 줍니다.

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.views.static import serve
from django.conf import settings
from django.contrib.auth.forms import AdminPasswordChangeForm

from mysite.forms import LoginForm, PasswordChangeForm
from mysite.views import UserCreateView, UserCreateDoneTV, SearchFormView, profile,  Search2ResultForm, contact
import django.contrib.auth.views

admin.autodiscover()

urlpatterns = [

	url(r'^admin/', include(admin.site.urls)),
	url(r'accounts/login/$', 'django.contrib.auth.views.login', {'authentication_form': LoginForm}, name='login'),
	url(r'accounts/password_change/$', 'django.contrib.auth.views.password_change', {'password_change_form': PasswordChangeForm}, name='password_change'),
	url(r'^accounts/', include('django.contrib.auth.urls')),
	url(r'accounts/register/$', UserCreateView.as_view(), name='register'),
	url(r'accounts/register/done/$', UserCreateDoneTV.as_view(), name='register_done'),	
	url(r'accounts/profile/$', profile),	
	url(r'^$', SearchFormView.as_view(), name='home'),
	url(r'^search/', Search2ResultForm.as_view(), name='search2'),
	url(r'^contact/', contact.as_view(), name='contact'),
	url(r'^Analyst/', include('Analyst.urls', namespace="Analyst")),
	url(r'^Disclosure/', include('Disclosure.urls', namespace="Disclosure")),
	url(r'^Issue/', include('Issue.urls', namespace="Issue")),
	url(r'^factbook/', include('factbook.urls', namespace="factbook")),
	url(r'^IRLink/', include('IRLink.urls', namespace="IRLink")),
	url(r'^ckeditor/', include('ckeditor_uploader.urls')),
	
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root =settings.STATIC_ROOT)

if settings.DEBUG:
	urlpatterns += [
	   url(r'media/(?P<path>.*)$',
             serve, {
                 'document_root' : settings.MEDIA_ROOT,
            }
        ),          
]

#정규표현식에 따라서 홈페이지의 url을 만들어 줍니다.

Issue/models.py
from __future__ import unicode_literals
from ckeditor.fields import RichTextField #text를 자유자재로 수정하기 위한 tool 사용
from ckeditor_uploader.fields import RichTextUploadingField #text를 자유자재로 수정하기 위한 tool 사용
from django.db import models
from django.utils import timezone #현재 시간을 가져오기 위한 도구
from Info.models import * #타 model import

# Create your models here.

class Issue_index(models.Model):	
	title = models.CharField(max_length=200) #글의 제목
	company = models.ForeignKey(company_name) #회사 이름
	text = RichTextUploadingField() #내용
	created_date = models.DateTimeField(default=timezone.now) #글의 생성일자
	published_date = models.DateTimeField(blank=True, null=True) #글의 게시일자

	def publish(self):
		self.published_date = timezone.now() #현재 일시 사용
		self.save()

	def __str__(self):
		return self.title	
	

Issue/forms.py
from django import forms

class PostSearchForm(forms.Form):
	search_word = forms.CharField(
		max_length=100,
		widget=forms.TextInput(
			attrs={
				'placeholder' : '  Type In Company Name or Ticker',
				'required': 'True',
			}
		)
	)
#검색을 위한 Form - 검색어를 입력받는 공간에 대한 정의
#placeholder - 배경에 글씨를 띄웁니다.
#required:True - 빈 칸을 허용하지 않습니다.

Issue/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from Info.models import *
from .forms import PostSearchForm
from Issue.models import Issue_index
from Info.models import company_name
from django.views.generic.edit import FormView
from django.db.models import Q
from django.shortcuts import render
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

# Create your views here.

#--- TemplateView

class Issue_Main(LoginRequiredMixin,FormView):
	model = Issue_index
	form_class = PostSearchForm
	template_name = 'Issue/Industry_Analysis.html'
	
	def get_context_data(self, **kwargs):
		context = super(Issue_Main, self).get_context_data(**kwargs)
		context['industry'] = Issue_index.objects.all().order_by('-created_date')
		
		return context

class Issue_Samsung(FormView):
	model = Issue_index
	form_class = PostSearchForm
	template_name = 'Issue/Industry_Analysis_samsung.html'
	
	def get_context_data(self, **kwargs):
		context = super(Issue_Samsung, self).get_context_data(**kwargs)
		context['industry'] = Issue_index.objects.filter(Q(company__second_industry_names__second_name = 'IT') | Q(company__second_industry_names__second_name = 'Semiconductor') | Q(company__second_industry_names__second_name = 'Tech_other')).order_by('-created_date')
		
		return context

class Issue_detail(FormView):
	
	form_class = PostSearchForm
	template_name = 'Issue/Industry_detail.html'
	
	def get_context_data(self, **kwargs):
		context = super(Issue_detail, self).get_context_data(**kwargs)
		context['industry'] = Issue_index.objects.get(pk=self.kwargs.get('pk'))
		
		return context

class Issue_Consumer(FormView):
	model = Issue_index
	form_class = PostSearchForm
	template_name = 'Issue/Industry_Consumer.html'

	def get_context_data(self, **kwargs):
		context = super(Issue_Consumer, self).get_context_data(**kwargs)
		context['con_industry'] = Issue_index.objects.filter(company__second_industry_names__parent__first_name = 'Consumer').order_by('-created_date')
		
		return context

class Issue_Apparel(FormView):
	model = Issue_index
	form_class = PostSearchForm
	template_name = 'Issue/Consumer/Industry_Apparel.html'

	def get_context_data(self, **kwargs):
		context = super(Issue_Apparel, self).get_context_data(**kwargs)
		context['app_industry'] = Issue_index.objects.filter(company__second_industry_names__second_name = 'Apparel').order_by('-created_date')
		
		return context

class Issue_Auto(FormView):
	model = Issue_index
	form_class = PostSearchForm
	template_name = 'Issue/Consumer/Industry_Auto.html'

	def get_context_data(self, **kwargs):
		context = super(Issue_Auto, self).get_context_data(**kwargs)
		context['aut_industry'] = Issue_index.objects.filter(company__second_industry_names__second_name = "Auto").order_by('-created_date')
		
		return context

class Issue_Cosmetics(FormView):
	model = Issue_index
	form_class = PostSearchForm
	template_name = 'Issue/Consumer/Industry_Cosmetics.html'

	def get_context_data(self, **kwargs):
		context = super(Issue_Cosmetics, self).get_context_data(**kwargs)
		context['cos_industry'] = Issue_index.objects.filter(company__second_industry_names__second_name = 'Cosmetics').order_by('-created_date')
		
		return context

class Issue_Distribution(FormView):
	model = Issue_index
	form_class = PostSearchForm
	template_name = 'Issue/Consumer/Industry_Distribution.html'

	def get_context_data(self, **kwargs):
		context = super(Issue_Distribution, self).get_context_data(**kwargs)
		context['dis_industry'] = Issue_index.objects.filter(company__second_industry_names__second_name = 'Distribution').order_by('-created_date')
		
		return context

class Issue_Entertainment(FormView):
	model = Issue_index
	form_class = PostSearchForm
	template_name = 'Issue/Consumer/Industry_Entertainment.html'

	def get_context_data(self, **kwargs):
		context = super(Issue_Entertainment, self).get_context_data(**kwargs)
		context['ent_industry'] = Issue_index.objects.filter(company__second_industry_names__second_name = 'Entertainment').order_by('-created_date')
		
		return context

class Issue_Education_Service(FormView):
	model = Issue_index
	form_class = PostSearchForm
	template_name = 'Issue/Consumer/Industry_Education_Service.html'

	def get_context_data(self, **kwargs):
		context = super(Issue_Education_Service, self).get_context_data(**kwargs)
		context['edu_industry'] = Issue_index.objects.filter(company__second_industry_names__second_name = 'Education_Service').order_by('-created_date')
		
		return context

class Issue_Food_Beverage(FormView):
	model = Issue_index
	form_class = PostSearchForm
	template_name = 'Issue/Consumer/Industry_Food&Beverage.html'

	def get_context_data(self, **kwargs):
		context = super(Issue_Food_Beverage, self).get_context_data(**kwargs)
		context['foo_industry'] = Issue_index.objects.filter(company__second_industry_names__second_name = 'Food_Beverage').order_by('-created_date')
		
		return context

class Issue_Game(FormView):
	model = Issue_index
	form_class = PostSearchForm
	template_name = 'Issue/Consumer/Industry_Game.html'

	def get_context_data(self, **kwargs):
		context = super(Issue_Game, self).get_context_data(**kwargs)
		context['gam_industry'] = Issue_index.objects.filter(company__second_industry_names__second_name = 'Game').order_by('-created_date')
		
		return context

class Issue_Media(FormView):
	model = Issue_index
	form_class = PostSearchForm
	template_name = 'Issue/Consumer/Industry_Media.html'

	def get_context_data(self, **kwargs):
		context = super(Issue_Media, self).get_context_data(**kwargs)
		context['med_industry'] = Issue_index.objects.filter(company__second_industry_names__second_name = 'Media').order_by('-created_date')
		
		return context

class Issue_Energy(FormView):
	model = Issue_index
	form_class = PostSearchForm
	template_name = 'Issue/Industry_Energy.html'

	def get_context_data(self, **kwargs):
		context = super(Issue_Energy, self).get_context_data(**kwargs)
		context['ene_industry'] = Issue_index.objects.filter(company__second_industry_names__parent__first_name = 'Energy').order_by('-created_date')
		
		return context

class Issue_Oil_Gas(FormView):
	model = Issue_index
	form_class = PostSearchForm
	template_name = 'Issue/Energy/Industry_Oil&Gas.html'

	def get_context_data(self, **kwargs):
		context = super(Issue_Oil_Gas, self).get_context_data(**kwargs)
		context['oil_industry'] = Issue_index.objects.filter(company__second_industry_names__second_name = 'Oil_Gas').order_by('-created_date')
		
		return context

class Issue_Petrochem(FormView):
	model = Issue_index
	form_class = PostSearchForm
	template_name = 'Issue/Energy/Industry_Petrochem.html'

	def get_context_data(self, **kwargs):
		context = super(Issue_Petrochem, self).get_context_data(**kwargs)
		context['pet_industry'] = Issue_index.objects.filter(company__second_industry_names__second_name = 'Petrochem').order_by('-created_date')
		
		return context

class Issue_Solar(FormView):
	model = Issue_index
	form_class = PostSearchForm
	template_name = 'Issue/Energy/Industry_Solar.html'

	def get_context_data(self, **kwargs):
		context = super(Issue_Solar, self).get_context_data(**kwargs)
		context['sol_industry'] = Issue_index.objects.filter(company__second_industry_names__second_name = 'Solar').order_by('-created_date')
		
		return context

class Issue_Utilities(FormView):
	model = Issue_index
	form_class = PostSearchForm
	template_name = 'Issue/Energy/Industry_Utilities.html'

	def get_context_data(self, **kwargs):
		context = super(Issue_Utilities, self).get_context_data(**kwargs)
		context['uti_industry'] = Issue_index.objects.filter(company__second_industry_names__second_name = 'Utilities').order_by('-created_date')
		
		return context

class Issue_Financial(FormView):
	model = Issue_index
	form_class = PostSearchForm
	template_name = 'Issue/Industry_Financial.html'

	def get_context_data(self, **kwargs):
		context = super(Issue_Financial, self).get_context_data(**kwargs)
		context['fin_industry'] = Issue_index.objects.filter(company__second_industry_names__parent__first_name = 'Financials').order_by('-created_date')
		
		return context

class Issue_Bank(FormView):
	model = Issue_index
	form_class = PostSearchForm
	template_name = 'Issue/Financial/Industry_Bank.html'

	def get_context_data(self, **kwargs):
		context = super(Issue_Bank, self).get_context_data(**kwargs)
		context['ban_industry'] = Issue_index.objects.filter(company__second_industry_names__second_name = 'Bank').order_by('-created_date')
		
		return context

class Issue_Securities(FormView):
	model = Issue_index
	form_class = PostSearchForm
	template_name = 'Issue/Financial/Industry_Securities.html'

	def get_context_data(self, **kwargs):
		context = super(Issue_Securities, self).get_context_data(**kwargs)
		context['sec_industry'] = Issue_index.objects.filter(company__second_industry_names__second_name = 'Securities').order_by('-created_date')
		
		return context

class Issue_Insurance(FormView):
	model = Issue_index
	form_class = PostSearchForm
	template_name = 'Issue/Financial/Industry_Insurance.html'

	def get_context_data(self, **kwargs):
		context = super(Issue_Insurance, self).get_context_data(**kwargs)
		context['ins_industry'] = Issue_index.objects.filter(company__second_industry_names__second_name = 'Insurance').order_by('-created_date')
		
		return context

class Issue_Other_Financial_Service(FormView):
	model = Issue_index
	form_class = PostSearchForm
	template_name = 'Issue/Financial/Industry_Other_Financial_Service.html'

	def get_context_data(self, **kwargs):
		context = super(Issue_Other_Financial_Service, self).get_context_data(**kwargs)
		context['ofs_industry'] = Issue_index.objects.filter(company__second_industry_names__second_name = 'Other_Financial_Service').order_by('-created_date')
		
		return context

class Issue_Healthcare(FormView):
	model = Issue_index
	form_class = PostSearchForm

Issue/templates/Issue/Consumer/Industry_Apparel.html
{% extends "base.html" %}

{% block title %}Industry_Apparel.html{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "css/Industry_Analysis.css" %}{% endblock %}

{% block content %}

		<form id="searchbox" action="{% url 'search2' %}" method="post"> {% csrf_token %}
		
				{{form.search_word}}
			
			<input id="submit" type="image" src="{% static "photo/search.png" %}">
		</form>

	<div id="wrap">
		<div id="box">
			<div id="aside">
				<nav id="asideMenu" >
					<ul> 
						<li class="main_li">
							<a class="menuLink" href="{% url 'Issue:All' %}">All</a>
						</li> 
						<li class="main_li">
							<a class="menuLink"  href="{% url 'Issue:Consumer' %}">Consumer</a>
							<ul class="submenu">
								<li><a class="sub_menuLink" href="{% url 'Issue:Apparel' %}">Apparel</a></li>
								<li><a class="sub_menuLink" href="{% url 'Issue:Auto' %}">Auto</a></li>
								<li><a class="sub_menuLink" href="{% url 'Issue:Cosmetics' %}">Cosmetics</a>
								<li><a class="sub_menuLink" href="{% url 'Issue:Distribution' %}">Distribution</a>
								<li><a class="sub_menuLink" href="{% url 'Issue:Entertainment' %}">Entertainment</a></li>
								<li><a class="sub_menuLink" href="{% url 'Issue:Education_Service' %}">Education Service</a>
								<li><a class="sub_menuLink" href="{% url 'Issue:Food_Beverage' %}">Food&Beverage</a>
								<li><a class="sub_menuLink" href="{% url 'Issue:Game' %}">Game</a>
								<li><a class="sub_menuLink" href="{% url 'Issue:Media' %}">Media</a>
							</ul>
						</li> 
						<li class="main_li">
							<a class="menuLink"  href="{% url 'Issue:Energy' %}">Energy</a>
							<ul class="submenu">
								<li><a class="sub_menuLink" href="{% url 'Issue:Oil&Gas' %}">Oil&Gas</a></li>
								<li><a class="sub_menuLink" href="{% url 'Issue:Petrochem' %}">Petrochem</a></li>
								<li><a class="sub_menuLink" href="{% url 'Issue:Solar' %}">Solar</a>
								<li><a class="sub_menuLink" href="{% url 'Issue:Utilities' %}">Utilities</a>
							</ul>
						</li> 
						<li class="main_li">
							<a class="menuLink"  href="{% url 'Issue:Financial' %}">Financials</a>
							<ul class="submenu">
								<li><a class="sub_menuLink" href="{% url 'Issue:Bank' %}">Bank</a></li>
								<li><a class="sub_menuLink" href="{% url 'Issue:Insurance' %}">Insurance</a></li>
								<li><a class="sub_menuLink" href="{% url 'Issue:Securities' %}">Securities</a>
								<li><a class="sub_menuLink" href="{% url 'Issue:Other_Financial_Service' %}">Other Financial Service</a>
							</ul>
						</li> 
						<li class="main_li">
							<a class="menuLink"  href="{% url 'Issue:Healthcare' %}">Healthcare</a>
							<ul class="submenu">
								<li><a class="sub_menuLink" href="{% url 'Issue:Medical_equipment' %}">Medical equipment</a></li>
								<li><a class="sub_menuLink" href="{% url 'Issue:Pharmaceuticals' %}">Pharmaceuticals</a></li>
								<li><a class="sub_menuLink" href="{% url 'Issue:Biotech' %}">Biotech</a>
							</ul>
						</li> 
						<li class="main_li">
							<a class="menuLink"  href="{% url 'Issue:Idustrials' %}">Industrials</a>
							<ul class="submenu">
								<li><a class="sub_menuLink" href="{% url 'Issue:Plant' %}">Plant</a></li>
								<li><a class="sub_menuLink" href="{% url 'Issue:Shipbuilding' %}">Shipbuilding</a></li>
							</ul>
						</li> 
						</li> 
						<li class="main_li">
							<a class="menuLink"  href="{% url 'Issue:Materials' %}">Materials</a>
							<ul class="submenu">
								<li><a class="sub_menuLink" href="{% url 'Issue:Construction' %}">Construction</a></li>
								<li><a class="sub_menuLink" href="{% url 'Issue:Steel' %}">Steel</a></li>
								<li><a class="sub_menuLink" href="{% url 'Issue:Chemical' %}">Chemical</a>
							</ul>
						</li> 
						</li> 
						<li class="main_li">
							<a class="menuLink"  href="{% url 'Issue:Other' %}">Other</a>
							<ul class="submenu">
								<li><a class="sub_menuLink" href="{% url 'Issue:Conglomerates_Holdco' %}">Conglomerates/Holdco</a></li>
								<li><a class="sub_menuLink" href="{% url 'Issue:Trading' %}">Trading</a></li>
								<li><a class="sub_menuLink" href="{% url 'Issue:Other_other' %}">Other</a>
							</ul>
						</li> 
						<li class="main_li">
							<a class="menuLink"  href="{% url 'Issue:Tech' %}">Tech</a>
							<ul class="submenu">
								<li><a class="sub_menuLink" href="{% url 'Issue:E_commerce' %}">E-commerce</a></li>
								<li><a class="sub_menuLink" href="{% url 'Issue:IT' %}">IT</a></li>
								<li><a class="sub_menuLink" href="{% url 'Issue:Machinery' %}">Machinery</a>
								<li><a class="sub_menuLink" href="{% url 'Issue:Semiconductor' %}">Semiconductor</a>
								<li><a class="sub_menuLink" href="{% url 'Issue:Display' %}">Display</a>
								<li><a class="sub_menuLink" href="{% url 'Issue:Internet_Service' %}">Internet Service</a>
								<li><a class="sub_menuLink" href="{% url 'Issue:Software' %}">Software</a>
								<li><a class="sub_menuLink" href="{% url 'Issue:Tech_other' %}">Other</a>
							</ul>
						</li> 
						<li class="main_li">
							<a class="menuLink"  href="{% url 'Issue:Telecom' %}">Telecom</a>
							<ul class="submenu">
								<li><a class="sub_menuLink" href="{% url 'Issue:Telecom_Service' %}">Telecom Service</a></li>
								<li><a class="sub_menuLink" href="{% url 'Issue:Telecom_Equipment' %}">Telecom Equipment</a></li>
							</ul>
						</li> s
					</ul> 
				</nav>
			</div>
			
			<div id=section>
				<div id="title"><h1 id="title_latest">Apparel Industry Analysis<h1></div>
				<div id="content">
					<table cellspacing="1" width="780">
						{% load el_pagination_tags %}
						{% paginate app_industry %}	
						{% for app_indu in app_industry %}
							<tr>
								<td class=bulletin><a href="{% url 'Issue:detail' app_indu.id %}" target="_blank">{{app_indu.title}}</a></td>
								<td class=date>{{app_indu.created_date}}</td>
							</tr>
						{% endfor %}
					</table>
				</div>
				<div id = "paging">				
				{% show_pages %}
				</div>
			</div>
		</div>
	</div>
{% endblock content %}	
	<div id="footer">
		<div id ="set">
			<div id = "foot_main">
				<div id = "foot_content">
					<table class="foot_table">
						<tbody>
						<tr><td>						
							<img id="email_logo" src="{% static "photo/envelope.png" %}"></a>
							<p id = foot_title>d.jee@bestir.net</p>
											
						</td></tr>
						<tr><td></td></tr>

						<tr><td>						
							<img id="phone_logo" src="{% static "photo/phone.png" %}"></a>
							<p id = foot_title>82-2-599-3359</p>

						</td></tr>
						<tr><td></td></tr>
						<tr><td>						
							<img id="placeholder_logo" src="{% static "photo/placeholder.png" %}"></a>
							<p id = foot_title>Test-bed Center 3rd Floor <br>Koscom Building<br>
							76 Yeouinaru-ro Yeongduengpo-g<br>
							Seoul, Korea	</p>
										
						</td></tr>

						</tbody>
					</table>
				</div>
				<p id =copy> Copyright &copy; 2017 - BESTIR. CO.LTD FACTBOOK -All Rights Reserved </p>
			</div>
		</div>
		
	</div>		
