Analyst/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.analyst_home.as_view(), name='Analyst_home'),
    url(r'^samsung', views.analyst_samsung.as_view(), name='Analyst_samsung'),
    url(r'^Analyst_more/(?P<pk>\d+)/', views.analyst_more.as_view(), name='more'),
    url(r'^page/(?P<pk>\d+)/', views.Analyst_detail.as_view(), name='detail'),
    url(r'^download_page/(?P<pk>\d+)/', views.Analyst_download.as_view(), name = 'down'),
    url(r'^download_page/$', views.Analyst_download_sam.as_view(), name = 'down_sam'),
    url(r'^download/(?P<id>\d+)/$', views.download, name='item'),
    url(r'^purchased/(?P<uid>\d+)/(?P<id>\d+)', views.purchased),
]

#정규표현식에 따라서 홈페이지의 url을 만들어 줍니다.

Disclosure/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.disclosure_home.as_view(), name='disclosure_home'),
    url(r'^samsung', views.disclosure_samsung.as_view(), name='disclosure_samsung'),
    url(r'^Disclosure_more/(?P<pk>\d+)/', views.disclosure_more.as_view(), name='more'),
    url(r'^page/(?P<pk>\d+)/', views.Disclosure_detail.as_view(), name='detail'),
    url(r'^download_page/(?P<pk>\d+)/', views.Disclosure_download.as_view(), name = 'down'),
    url(r'^download_page/$', views.Disclosure_download_sam.as_view(), name = 'down_sam'),
    url(r'^download/(?P<id>\d+)/$', views.download, name='item'),
    url(r'^purchased/(?P<uid>\d+)/(?P<id>\d+)', views.purchased),
]

#정규표현식에 따라서 홈페이지의 url을 만들어 줍니다.

IRLink/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.irlink_home.as_view(), name='IRLink_home'),
    url(r'^IRLink_more/(?P<pk>\d+)/', views.irlink_more.as_view(), name='more'),
    url(r'^page/(?P<pk>\d+)/', views.irlink_detail.as_view(), name='detail'),
]

#정규표현식에 따라서 홈페이지의 url을 만들어 줍니다.

Issue/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.Issue_Main.as_view(), name='Industry_Analysis'),
    url(r'samsung', views.Issue_Samsung.as_view(), name='Industry_Analysis_samsung'),
    
    url(r'^all/', views.Issue_Main.as_view(), name='All'),
    url(r'^page/(?P<pk>\d+)/', views.Issue_detail.as_view(), name='detail'),
    url(r'^Industry_more/(?P<pk>\d+)/', views.Issue_Analysis_more.as_view(), name='more'),

    url(r'^Consumer/Apparel', views.Issue_Apparel.as_view(), name='Apparel'),
    url(r'^Consumer/Auto', views.Issue_Auto.as_view(), name='Auto'),
    url(r'^Consumer/Cosmetics', views.Issue_Cosmetics.as_view(), name='Cosmetics'),
    url(r'^Consumer/Distribution', views.Issue_Distribution.as_view(), name='Distribution'),
    url(r'^Consumer/Etertainment', views.Issue_Entertainment.as_view(), name='Entertainment'),
    url(r'^Consumer/Education_Service', views.Issue_Education_Service.as_view(), name='Education_Service'),
    url(r'^Consumer/Food_Beverage', views.Issue_Food_Beverage.as_view(), name='Food_Beverage'),
    url(r'^Consumer/Game', views.Issue_Game.as_view(), name='Game'),
    url(r'^Consumer/Media', views.Issue_Media.as_view(), name='Media'),
    url(r'^Consumer/', views.Issue_Consumer.as_view(), name='Consumer'),

    url(r'^Energy/Oil_Gas', views.Issue_Oil_Gas.as_view(), name='Oil&Gas'),
    url(r'^Energy/Petrochem', views.Issue_Petrochem.as_view(), name='Petrochem'),
    url(r'^Energy/Solar', views.Issue_Solar.as_view(), name='Solar'),
    url(r'^Energy/Utilities', views.Issue_Utilities.as_view(), name='Utilities'),
    url(r'^Energy/', views.Issue_Energy.as_view(), name='Energy'),

    url(r'^Financial/Bank', views.Issue_Bank.as_view(), name='Bank'),
    url(r'^Financial/Insurance', views.Issue_Insurance.as_view(), name='Insurance'),
    url(r'^Financial/Securities', views.Issue_Securities.as_view(), name='Securities'),
    url(r'^Financial/Other_Financial_Service', views.Issue_Other_Financial_Service.as_view(), name='Other_Financial_Service'),
    url(r'^Financial/', views.Issue_Financial.as_view(), name='Financial'),

    url(r'^Healthcare/Medical_equipment', views.Issue_Medical_equipment.as_view(), name='Medical_equipment'),
    url(r'^Healthcare/Pharmaceuticals', views.Issue_Pharmaceuticals.as_view(), name='Pharmaceuticals'),
    url(r'^Healthcare/Biotech', views.Issue_Biotech.as_view(), name='Biotech'),
    url(r'^Healthcare/', views.Issue_Healthcare.as_view(), name='Healthcare'),

    url(r'^Idustrials/Plant', views.Issue_Plant.as_view(), name='Plant'),
    url(r'^Idustrials/Shipbuilding', views.Issue_Shipbuilding.as_view(), name='Shipbuilding'),
    url(r'^Idustrials/', views.Issue_Idustrials.as_view(), name='Idustrials'),

    url(r'^Materials/Construction', views.Issue_Construction.as_view(), name='Construction'),
    url(r'^Materials/Steel', views.Issue_Steel.as_view(), name='Steel'),
    url(r'^Materials/Chemical', views.Issue_Chemical.as_view(), name='Chemical'),
    url(r'^Materials/', views.Issue_Materials.as_view(), name='Materials'),


    url(r'^Other/Conglomerates_Holdco', views.Issue_Conglomerates_Holdco.as_view(), name='Conglomerates_Holdco'),
    url(r'^Other/Trading', views.Issue_Trading.as_view(), name='Trading'),
    url(r'^Other/Other_other', views.Issue_Other_other.as_view(), name='Other_other'),
    url(r'^Other/', views.Issue_Other.as_view(), name='Other'),

    url(r'^Tech/E_commerce', views.Issue_E_commerce.as_view(), name='E_commerce'),
    url(r'^Tech/IT', views.Issue_IT.as_view(), name='IT'),
    url(r'^Tech/Machinery', views.Issue_Machinery.as_view(), name='Machinery'),
    url(r'^Tech/Semiconductor', views.Issue_Semiconductor.as_view(), name='Semiconductor'),
    url(r'^Tech/Display', views.Issue_Display.as_view(), name='Display'),
    url(r'^Tech/Internet_Service', views.Issue_Internet_Service.as_view(), name='Internet_Service'),
    url(r'^Tech/Software', views.Issue_Software.as_view(), name='Software'),
    url(r'^Tech/Tech_other', views.Issue_Tech_other.as_view(), name='Tech_other'),
    url(r'^Tech/', views.Issue_Tech.as_view(), name='Tech'),

    url(r'^Telecom/Telecom_Service', views.Issue_Telecom_Service.as_view(), name='Telecom_Service'),
    url(r'^Telecom/Telecom_Equipment', views.Issue_Telecom_Equipment.as_view(), name='Telecom_Equipment'),
    url(r'^Telecom', views.Issue_Telecom.as_view(), name='Telecom'),
]

#정규표현식에 따라서 홈페이지의 url을 만들어 줍니다.

factbook/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.factbook_list.as_view(), name='factbook_list'),
    url(r'^more/(?P<pk>\d+)/', views.factbook_more.as_view(), name='factbook_more'),
    url(r'^detail/', views.factbook_detail.as_view(), name='factbook_detail'),
    url(r'^download_page/(?P<pk>\d+)/', views.factbook_download.as_view(), name = 'down'),
    url(r'^download_page/$', views.factbook_download_sam.as_view(), name = 'down_sam'),
    url(r'^download/(?P<id>\d+)/$', views.download, name='item'),
    url(r'^purchased/(?P<uid>\d+)/(?P<id>\d+)', views.purchased),
]

#정규표현식에 따라서 홈페이지의 url을 만들어 줍니다.

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.views.static import serve
from django.conf import settings
from django.contrib.auth.forms import AdminPasswordChangeForm

from mysite.forms import LoginForm, PasswordChangeForm
from mysite.views import UserCreateView, UserCreateDoneTV, SearchFormView, profile,  Search2ResultForm, contact
import django.contrib.auth.views

admin.autodiscover()

urlpatterns = [

	url(r'^admin/', include(admin.site.urls)),
	url(r'accounts/login/$', 'django.contrib.auth.views.login', {'authentication_form': LoginForm}, name='login'),
	url(r'accounts/password_change/$', 'django.contrib.auth.views.password_change', {'password_change_form': PasswordChangeForm}, name='password_change'),
	url(r'^accounts/', include('django.contrib.auth.urls')),
	url(r'accounts/register/$', UserCreateView.as_view(), name='register'),
	url(r'accounts/register/done/$', UserCreateDoneTV.as_view(), name='register_done'),	
	url(r'accounts/profile/$', profile),	
	url(r'^$', SearchFormView.as_view(), name='home'),
	url(r'^search/', Search2ResultForm.as_view(), name='search2'),
	url(r'^contact/', contact.as_view(), name='contact'),
	url(r'^Analyst/', include('Analyst.urls', namespace="Analyst")),
	url(r'^Disclosure/', include('Disclosure.urls', namespace="Disclosure")),
	url(r'^Issue/', include('Issue.urls', namespace="Issue")),
	url(r'^factbook/', include('factbook.urls', namespace="factbook")),
	url(r'^IRLink/', include('IRLink.urls', namespace="IRLink")),
	url(r'^ckeditor/', include('ckeditor_uploader.urls')),
	
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root =settings.STATIC_ROOT)

if settings.DEBUG:
	urlpatterns += [
	   url(r'media/(?P<path>.*)$',
             serve, {
                 'document_root' : settings.MEDIA_ROOT,
            }
        ),          
]

#정규표현식에 따라서 홈페이지의 url을 만들어 줍니다.

Analyst/models.py
from __future__ import unicode_literals
from ckeditor.fields import RichTextField #text를 자유자재로 수정하기 위한 tool 사용
from ckeditor_uploader.fields import RichTextUploadingField #text를 자유자재로 수정하기 위한 tool 사용
from django.db import models
from django.utils import timezone #현재 시간을 가져오기 위한 도구
from Info.models import * #타 model import
from django.contrib.auth.models import User #model에서 User를 사용하기 위한 도구

class analyst_index(models.Model):	
	title = models.CharField(max_length=200) #글의 제목
	company = models.ForeignKey(company_name) #회사 이름
	text = RichTextUploadingField() #내용
	anal_document = models.FileField(null = True) #문서 업로드
	location = models.CharField(max_length = 250) #문서이름
	price = models.DecimalField(decimal_places = 2, max_digits=7) #문서에 대한 가격
	created_date = models.DateTimeField(default=timezone.now) #글의 생성일자
	published_date = models.DateTimeField(blank=True, null=True) #글의 게시일자

	def publish(self):
		self.published_date = timezone.now() #현재 일시 사용
		self.save()

	def __str__(self):
		return self.title #다른 모델에서 자신의 모델을 부를 때 설정하지 않았을 시에 title반환

class analyst_Purchase(models.Model): #paypal에서 제공된 코드
	resource = models.ForeignKey(analyst_index)
	purchaser = models.ForeignKey(User)
	purchased_at = models.DateTimeField(auto_now_add=True)
	tx = models.CharField(max_length=250)
	

Analyst/forms.py
from django import forms

class PostSearchForm(forms.Form):
	search_word = forms.CharField(
		max_length=100,
		widget=forms.TextInput(
			attrs={
				'placeholder' : '  Type In Company Name or Ticker',
				'required': 'True',
			}
		)
	)

#검색을 위한 Form - 검색어를 입력받는 공간에 대한 정의
#placeholder - 배경에 글씨를 띄웁니다.
#required:True - 빈 칸을 허용하지 않습니다.

Analyst/views.py
from django.shortcuts import render
from django.views.generic.edit import FormView #필요한 view를 불러옵니다.
from django.views.generic.base import TemplateView #필요한 view를 불러옵니다.
from django.contrib.auth.mixins import LoginRequiredMixin #로그인을 필요하게 만들어줍니다.
from .forms import PostSearchForm
from Analyst.models import analyst_index, analyst_Purchase #model import
from Info.models import company_name #model import
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger #page기능을 불러옵니다.

from django.contrib.auth.decorators import login_required #로그인을 필요하게 만들어줍니다.
from django.shortcuts import render, render_to_response, get_object_or_404 #함수형에서 template으로 반환할 시에 사용합니다.
from django.conf import settings
from django.template import RequestContext
from . import paypal
from django.core.files.storage import FileSystemStorage
from django.http import HttpResponse, Http404
from django.contrib.auth.models import User

# Create your views here.

class analyst_home(LoginRequiredMixin,FormView): #Login을 하지 않으면 진행할 수 없게 LoginRequiredMixin을 추가하였습니다.
	model = analyst_index #기본 모델입니다.
	form_class = PostSearchForm #현재 FormView에서 사용하는 Form입니다.
	template_name = 'Analyst/Analyst_home.html' #현재 View에서 보여지는 template위치입니다.

	def get_context_data(self, **kwargs):
		context = super(analyst_home, self).get_context_data(**kwargs)
		context['All'] = analyst_index.objects.all().order_by('-created_date')
		
		return context
#context기능으로 필요한 정보를 가공합니다.

class analyst_samsung(FormView):
	model = analyst_index
	form_class = PostSearchForm
	template_name = 'Analyst/Analyst_samsung.html'

	def get_context_data(self, **kwargs):
		samsung = "Samsung Electronics"
		context = super(analyst_samsung, self).get_context_data(**kwargs)
		context['samsung'] = analyst_index.objects.filter(company__title = samsung).order_by('-created_date')
		
		return context

class analyst_more(FormView):
	model = analyst_index
	form_class = PostSearchForm
	template_name = 'Analyst/Analyst_more.html'
	
	def get_context_data(self, **kwargs):
		context = super(analyst_more, self).get_context_data(**kwargs)
		context['sch_ana'] = analyst_index.objects.filter(company__pk=self.kwargs['pk']).order_by('-created_date')
		context['comp_name'] = company_name.objects.get(pk=self.kwargs['pk'])
		
		return context

class Analyst_detail(FormView):
	form_class = PostSearchForm
	template_name = 'Analyst/Analyst_detail.html'
	
	def get_context_data(self, **kwargs):
		context = super(Analyst_detail, self).get_context_data(**kwargs)
		context['industry'] = analyst_index.objects.get(pk=self.kwargs.get('pk'))
		
		return context

class Analyst_download(TemplateView):
	template_name = 'Analyst/down.html'

	def get_context_data(self, **kwargs):
		context = super(Analyst_download, self).get_context_data(**kwargs)
		context['list'] = analyst_index.objects.filter(pk=self.kwargs['pk'])
	
		return context

class Analyst_download_sam(LoginRequiredMixin,TemplateView):
	template_name = 'Analyst/down_sam.html'

	def get_context_data(self, **kwargs):
		samsung = "Samsung Electronics"
		context = super(Analyst_download_sam, self).get_context_data(**kwargs)
		context['list'] = analyst_index.objects.filter(company__title = samsung)
	
		return context

@login_required
def download(request, id): #paypal에서 제공되는 코드입니다.
	resource = get_object_or_404(analyst_index, pk =id)
	try:
		purchased = analyst_Purchase.objects.get(resource=resource, purchaser = request.user )
		fs = FileSystemStorage()
		filename = resource.location
		if fs.exists(filename):
			with fs.open(filename) as pdf:
				response = HttpResponse(pdf, content_type=['application/pdf', 'application/zip'])
				response['Content-Disposition'] = 'attachment; filename=%s' % resource.location
				return response
	except analyst_Purchase.DoesNotExist:
		return render_to_response('Analyst/purchase.html', { 'resource': resource, 'paypal_url': settings.PAYPAL_URL , 'paypal_email': settings.PAYPAL_EMAIL, 'paypal_return_url': settings.PAYPAL_RETURN_URL }, context_instance=RequestContext(request))

def purchased(request, uid, id):
	resource = get_object_or_404(analyst_index, pk =id)
	user = get_object_or_404(User, pk=uid)
	if 'tx' in request.GET:
		tx = request.GET['tx']
		try:
			existing = analyst_Purchase.objects.get(tx =tx)
			return render_to_response('error.html', { 'error': "Duplicate transaction"}, context_instance=RequestContext(request) )
		except analyst_Purchase.DoesNotExist:
			result = paypal.Verify(tx)
			if result.success() and resource.price == result.amount():
				purchase = analyst_Purchase(resource = resource, purchaser = user, tx =tx)
				purchase.save()
				return render_to_response('Analyst/purchased.html', {'resource':resource }, context_instance=RequestContext(request))
			else:
				return render_to_response('error.html', { 'error': "Failed to validate payment" }, context_instance=RequestContext(request))

	else:
		return render_to_response('error.html', {'error': "No transaction specified" }, context_instance=RequestContext(request))

Analyst/templates/Analyst/Analyst_detail.html
<head>
	<title>Analyst_detail.html</title>
	{% load staticfiles %}
	<link rel = "stylesheet" type="text/css" href={% static "css/Analyst_detail.css" %} />

</head>
	
	<div id="wrap">
		<div id="box">
			<div id="all_section">
				
				<div id="company_info">
					<h2 id=name>{{industry.title}}</h2> 
					<h3 id=num>{{industry.company.Ticker_Number}}</h3>
					<a href="{% url 'Analyst:down' industry.id %} " target="_blank"><img id="pdf_logo" src="{% static "photo/pdf_icon.png" %}"></a>
				</div>
				
				<div id="Disclosure" class="section">
					{{industry.text|safe}}
				</div>
			</div>
		</div>
	</div>

Analyst/templates/Analyst/Analyst_home.html
{% extends "base.html" %}

{% block title %}Analyst_home.html{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "css/Analyst_home.css" %}{% endblock %}

{% block content %}

		<form id="searchbox" action="{% url 'search2' %}" method="post"> {% csrf_token %}
		
				{{form.search_word}}
			
			<input id="submit" type="image" src="{% static "photo/search.png" %}">
		</form>
	
	<div id="wrap">
		<div id="box">
			<div id="aside">
				<nav id="asideMenu" >
					<ul> 
						<li><a class="menuLink"  href="{% url 'factbook:factbook_list' %}">Factbook</a></li> 
						<li><a class="menuLink"  href="{% url 'Disclosure:disclosure_home' %}">Disclosures</a></li> 
						<li><a class="menuLink"  href="{% url 'Analyst:Analyst_home' %}">Analyst Report</a></li> 
						<li><a class="menuLink" href="{% url 'Issue:Industry_Analysis' %}">Industry Info</a></li>
						<li><a class="menuLink" href="{% url 'IRLink:IRLink_home' %}">IR Link</a></li>
					</ul> 
				</nav>
			</div>

			<div id="all_section">
				
				<div id="company_info">
					<h2 id=name>Latest Analyst Report</h2> 
				</div>
				
				<div id="Analyst" class="section">
					<table class="subtitle">
						<tbody>
                                               {% load el_pagination_tags %}
	                                       {% paginate All %}	
						{% for all in All %}
							<tr>
								<td class=bulletin><a href="{% url 'Analyst:detail' all.id %}" target="_blank"> {{all.title}}</a></td>
								<td class=date>{{all.created_date}}</td>
							</tr>
						{% endfor %}
                                             
						</tbody>
					</table>     
				</div>
				<div id = "paging">				
				{% show_pages %}
				</div>
			</div>
		</div>
	</div>
{% endblock content %}

Analyst/templates/Analyst/Analyst_more.html
{% extends "base.html" %}

{% block title %}Analyst_home.html{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "css/Analyst_samsung.css" %}{% endblock %}

{% block content %}

		<form id="searchbox" action="{% url 'search2' %}" method="post"> {% csrf_token %}
		
				<input id = id_search_word type="text" placeholder="  Type In Company Name or Ticker" maxlength="100" required="True" name="search_word">
			
			<input id="submit" type="image" src="{% static "photo/search.png" %}">
		</form>
	
	<div id="wrap">
		<div id="box">
			<div id="aside">
				<nav id="asideMenu" >
					<ul> 
						<li><a class="menuLink"  href="{% url 'factbook:factbook_more' comp_name.id %}">Factbook</a></li> 
						<li><a class="menuLink"  href="{% url 'Disclosure:more' comp_name.id %}">Disclosures</a></li> 
						<li><a class="menuLink"  href="{% url 'Analyst:more' comp_name.id %}">Analyst Report</a></li> 
						<li><a class="menuLink" href="{% url 'Issue:more' comp_name.id %}">Industry Info</a></li> 
						<li><a class="menuLink" href="{% url 'IRLink:more' comp_name.id %}">IR Link</a></li>
					</ul> 

				</nav>
			</div>

			<div id="all_section">
				
				<div id="company_info">
					<h2 id=name>{{comp_name.title}}</h2> 
					<h3 id=num>{{comp_name.Ticker_Number}}</h3>
				</div>
				
				<div id="Analyst" class="section">
					<a class="menu_title" href="">Analyst</a>

					<table class="subtitle">
						<tbody>
						{% load el_pagination_tags %}
						{% paginate sch_ana %}
						{% for ana in sch_ana %}
							<tr>
								<td class=bulletin><a href="{% url 'Analyst:detail' ana.id %}" target="_blank"> {{ana.title}}</a></td>
								<td class=date>{{ana.created_date}}</td>
							</tr>
						{% endfor %}
						
						</tbody>
					</table>
				</div>
				<div id = "paging">				
				{% show_pages %}
				</div>
			</div>
		</div>
	</div>
{% endblock content %}

Analyst/templates/Analyst/Analyst_samsung.html
{% extends "base.html" %}

{% block title %}Analyst_home.html{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "css/Analyst_samsung.css" %}{% endblock %}

{% block content %}

		<form id="searchbox" action="{% url 'search2' %}" method="post"> {% csrf_token %}
		
				{{form.search_word}}
			
			<input id="submit" type="image" src="{% static "photo/search.png" %}">
		</form>
	
	<div id="wrap">
		<div id="box">
			<div id="aside">
				<nav id="asideMenu" >
					<ul> 
						<li><a class="menuLink"  href="{% url 'factbook:factbook_list' %}">Factbook</a></li> 
						<li><a class="menuLink"  href="{% url 'Disclosure:disclosure_samsung' %}">Disclosures</a></li> 
						<li><a class="menuLink"  href="{% url 'Analyst:Analyst_samsung' %}">Analyst Report</a></li> 
						<li><a class="menuLink" href="{% url 'Issue:Industry_Analysis_samsung' %}">Industry Info</a></li>
						<li><a class="menuLink" href="{% url 'IRLink:IRLink_home' %}">IR Link</a></li>
					</ul> 
				</nav>
			</div>

			<div id="all_section">
				
				<div id="company_info">
					<h2 id=name>Samsung Electronics</h2> 
					<h3 id=num>KS005930</h3>
				</div>
				
				<div id="Analyst" class="section">
					<a class="menu_title" href="">Analyst</a>

					<table class="subtitle">
						<tbody>
                                               {% load el_pagination_tags %}
	                                       {% paginate samsung %}	
						{% for sam in samsung %}
							<tr>
								<td class=bulletin><a href="{% url 'Analyst:detail' sam.id %}" target="_blank"> {{sam.title}}</a></td>
								<td class=date>{{sam.created_date}}</td>
							</tr>
						{% endfor %}
                                             
						</tbody>
					</table>     
				</div>
				<div id = "paging">				
				{% show_pages %}
				</div>
			</div>
		</div>
	</div>
{% endblock content %}

Analyst/templates/Analyst/down.html
<head>
	<title>down.html</title>
	{% load staticfiles %}
	<link rel = "stylesheet" type="text/css" href={% static "css/down.css" %} />

</head>
		
<div id = "wrap">
	<div id = "box">
		<div id = "Avail_Resource">		
			<p>Available Resources</p>
		</div>
		<div id = "item_list">
			<ul>
			{% for item in list %}
			<li><a href="{% url 'Analyst:item' item.id %}">{{ item.company.title }} - ${{ item.price|floatformat:2 }}</a></li>
			{% endfor %}
			</ul>
		</div>
		<div id = "your_prof">
			<a href="/accounts/profile">Your profile</a>
		</div>
</div>

Analyst/templates/Analyst/down_sam.html
<head>
	<title>down_sam.html</title>
	{% load staticfiles %}
	<link rel = "stylesheet" type="text/css" href={% static "css/down.css" %} />

</head>
		
<div id = "wrap">
	<div id = "box">
		<div id = "Avail_Resource">		
			<p>Available Resources</p>
		</div>
		<div id = "item_list">
			<ul>
			{% for item in list %}
			<li><a href="{% url 'factbook:item' item.id %}">{{ item.company.title }} - ${{ item.price|floatformat:2 }}</a></li>
			{% endfor %}
			</ul>
		</div>
		<div id = "your_prof">
			<a href="/accounts/profile">Your profile</a>
		</div>
</div>

Analyst/templates/Analyst/purchase.html
<html>
<body>
<p>Purchase <b>{{ resource.company.title }}</b> for <b>${{ resource.price|floatformat:2 }}</b></p>
<p>
<form action="{{ paypal_url }}" method="post">
  <input type="hidden" name="amount" value="{{ resource.price }}">
  <input type="hidden" name="cmd" value="_xclick">
  <input type="hidden" name="business" value="{{ paypal_email }}">
  <input type="hidden" name="item_name" value="{{ resource.name }}">
  <input type="hidden" name="currency_code" value="USD">
  <input type="hidden" name="return" value="{{ paypal_return_url }}/Analyst/purchased/{{ user.id }}/{{resource.id}}">
  <input type="hidden" name="cancel_return" value="{{ paypal_return_url }}/">
  <input type="image" src="http://www.paypal.com/en_AU/i/btn/x-click-but01.gif" name="submit" alt="Make payments with PayPal - it's fast, free and secure!">
</form>
</p>
</body>
</html>

Analyst/templates/Analyst/purchased.html
<html>
<body>
<p>You have successfully purchased <b>{{ resource.company.title }}</b></p>
<p><a href="/Analyst/download/{{ resource.id }}/">Download Now</a></p>
</body>
</html>