Analyst/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.analyst_home.as_view(), name='Analyst_home'),
    url(r'^samsung', views.analyst_samsung.as_view(), name='Analyst_samsung'),
    url(r'^Analyst_more/(?P<pk>\d+)/', views.analyst_more.as_view(), name='more'),
    url(r'^page/(?P<pk>\d+)/', views.Analyst_detail.as_view(), name='detail'),
    url(r'^download_page/(?P<pk>\d+)/', views.Analyst_download.as_view(), name = 'down'),
    url(r'^download_page/$', views.Analyst_download_sam.as_view(), name = 'down_sam'),
    url(r'^download/(?P<id>\d+)/$', views.download, name='item'),
    url(r'^purchased/(?P<uid>\d+)/(?P<id>\d+)', views.purchased),
]

#정규표현식에 따라서 홈페이지의 url을 만들어 줍니다.

Disclosure/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.disclosure_home.as_view(), name='disclosure_home'),
    url(r'^samsung', views.disclosure_samsung.as_view(), name='disclosure_samsung'),
    url(r'^Disclosure_more/(?P<pk>\d+)/', views.disclosure_more.as_view(), name='more'),
    url(r'^page/(?P<pk>\d+)/', views.Disclosure_detail.as_view(), name='detail'),
    url(r'^download_page/(?P<pk>\d+)/', views.Disclosure_download.as_view(), name = 'down'),
    url(r'^download_page/$', views.Disclosure_download_sam.as_view(), name = 'down_sam'),
    url(r'^download/(?P<id>\d+)/$', views.download, name='item'),
    url(r'^purchased/(?P<uid>\d+)/(?P<id>\d+)', views.purchased),
]

#정규표현식에 따라서 홈페이지의 url을 만들어 줍니다.

IRLink/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.irlink_home.as_view(), name='IRLink_home'),
    url(r'^IRLink_more/(?P<pk>\d+)/', views.irlink_more.as_view(), name='more'),
    url(r'^page/(?P<pk>\d+)/', views.irlink_detail.as_view(), name='detail'),
]

#정규표현식에 따라서 홈페이지의 url을 만들어 줍니다.

Issue/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.Issue_Main.as_view(), name='Industry_Analysis'),
    url(r'samsung', views.Issue_Samsung.as_view(), name='Industry_Analysis_samsung'),
    
    url(r'^all/', views.Issue_Main.as_view(), name='All'),
    url(r'^page/(?P<pk>\d+)/', views.Issue_detail.as_view(), name='detail'),
    url(r'^Industry_more/(?P<pk>\d+)/', views.Issue_Analysis_more.as_view(), name='more'),

    url(r'^Consumer/Apparel', views.Issue_Apparel.as_view(), name='Apparel'),
    url(r'^Consumer/Auto', views.Issue_Auto.as_view(), name='Auto'),
    url(r'^Consumer/Cosmetics', views.Issue_Cosmetics.as_view(), name='Cosmetics'),
    url(r'^Consumer/Distribution', views.Issue_Distribution.as_view(), name='Distribution'),
    url(r'^Consumer/Etertainment', views.Issue_Entertainment.as_view(), name='Entertainment'),
    url(r'^Consumer/Education_Service', views.Issue_Education_Service.as_view(), name='Education_Service'),
    url(r'^Consumer/Food_Beverage', views.Issue_Food_Beverage.as_view(), name='Food_Beverage'),
    url(r'^Consumer/Game', views.Issue_Game.as_view(), name='Game'),
    url(r'^Consumer/Media', views.Issue_Media.as_view(), name='Media'),
    url(r'^Consumer/', views.Issue_Consumer.as_view(), name='Consumer'),

    url(r'^Energy/Oil_Gas', views.Issue_Oil_Gas.as_view(), name='Oil&Gas'),
    url(r'^Energy/Petrochem', views.Issue_Petrochem.as_view(), name='Petrochem'),
    url(r'^Energy/Solar', views.Issue_Solar.as_view(), name='Solar'),
    url(r'^Energy/Utilities', views.Issue_Utilities.as_view(), name='Utilities'),
    url(r'^Energy/', views.Issue_Energy.as_view(), name='Energy'),

    url(r'^Financial/Bank', views.Issue_Bank.as_view(), name='Bank'),
    url(r'^Financial/Insurance', views.Issue_Insurance.as_view(), name='Insurance'),
    url(r'^Financial/Securities', views.Issue_Securities.as_view(), name='Securities'),
    url(r'^Financial/Other_Financial_Service', views.Issue_Other_Financial_Service.as_view(), name='Other_Financial_Service'),
    url(r'^Financial/', views.Issue_Financial.as_view(), name='Financial'),

    url(r'^Healthcare/Medical_equipment', views.Issue_Medical_equipment.as_view(), name='Medical_equipment'),
    url(r'^Healthcare/Pharmaceuticals', views.Issue_Pharmaceuticals.as_view(), name='Pharmaceuticals'),
    url(r'^Healthcare/Biotech', views.Issue_Biotech.as_view(), name='Biotech'),
    url(r'^Healthcare/', views.Issue_Healthcare.as_view(), name='Healthcare'),

    url(r'^Idustrials/Plant', views.Issue_Plant.as_view(), name='Plant'),
    url(r'^Idustrials/Shipbuilding', views.Issue_Shipbuilding.as_view(), name='Shipbuilding'),
    url(r'^Idustrials/', views.Issue_Idustrials.as_view(), name='Idustrials'),

    url(r'^Materials/Construction', views.Issue_Construction.as_view(), name='Construction'),
    url(r'^Materials/Steel', views.Issue_Steel.as_view(), name='Steel'),
    url(r'^Materials/Chemical', views.Issue_Chemical.as_view(), name='Chemical'),
    url(r'^Materials/', views.Issue_Materials.as_view(), name='Materials'),


    url(r'^Other/Conglomerates_Holdco', views.Issue_Conglomerates_Holdco.as_view(), name='Conglomerates_Holdco'),
    url(r'^Other/Trading', views.Issue_Trading.as_view(), name='Trading'),
    url(r'^Other/Other_other', views.Issue_Other_other.as_view(), name='Other_other'),
    url(r'^Other/', views.Issue_Other.as_view(), name='Other'),

    url(r'^Tech/E_commerce', views.Issue_E_commerce.as_view(), name='E_commerce'),
    url(r'^Tech/IT', views.Issue_IT.as_view(), name='IT'),
    url(r'^Tech/Machinery', views.Issue_Machinery.as_view(), name='Machinery'),
    url(r'^Tech/Semiconductor', views.Issue_Semiconductor.as_view(), name='Semiconductor'),
    url(r'^Tech/Display', views.Issue_Display.as_view(), name='Display'),
    url(r'^Tech/Internet_Service', views.Issue_Internet_Service.as_view(), name='Internet_Service'),
    url(r'^Tech/Software', views.Issue_Software.as_view(), name='Software'),
    url(r'^Tech/Tech_other', views.Issue_Tech_other.as_view(), name='Tech_other'),
    url(r'^Tech/', views.Issue_Tech.as_view(), name='Tech'),

    url(r'^Telecom/Telecom_Service', views.Issue_Telecom_Service.as_view(), name='Telecom_Service'),
    url(r'^Telecom/Telecom_Equipment', views.Issue_Telecom_Equipment.as_view(), name='Telecom_Equipment'),
    url(r'^Telecom', views.Issue_Telecom.as_view(), name='Telecom'),
]

#정규표현식에 따라서 홈페이지의 url을 만들어 줍니다.

factbook/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.factbook_list.as_view(), name='factbook_list'),
    url(r'^more/(?P<pk>\d+)/', views.factbook_more.as_view(), name='factbook_more'),
    url(r'^detail/', views.factbook_detail.as_view(), name='factbook_detail'),
    url(r'^download_page/(?P<pk>\d+)/', views.factbook_download.as_view(), name = 'down'),
    url(r'^download_page/$', views.factbook_download_sam.as_view(), name = 'down_sam'),
    url(r'^download/(?P<id>\d+)/$', views.download, name='item'),
    url(r'^purchased/(?P<uid>\d+)/(?P<id>\d+)', views.purchased),
]

#정규표현식에 따라서 홈페이지의 url을 만들어 줍니다.

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.views.static import serve
from django.conf import settings
from django.contrib.auth.forms import AdminPasswordChangeForm

from mysite.forms import LoginForm, PasswordChangeForm
from mysite.views import UserCreateView, UserCreateDoneTV, SearchFormView, profile,  Search2ResultForm, contact
import django.contrib.auth.views

admin.autodiscover()

urlpatterns = [

	url(r'^admin/', include(admin.site.urls)),
	url(r'accounts/login/$', 'django.contrib.auth.views.login', {'authentication_form': LoginForm}, name='login'),
	url(r'accounts/password_change/$', 'django.contrib.auth.views.password_change', {'password_change_form': PasswordChangeForm}, name='password_change'),
	url(r'^accounts/', include('django.contrib.auth.urls')),
	url(r'accounts/register/$', UserCreateView.as_view(), name='register'),
	url(r'accounts/register/done/$', UserCreateDoneTV.as_view(), name='register_done'),	
	url(r'accounts/profile/$', profile),	
	url(r'^$', SearchFormView.as_view(), name='home'),
	url(r'^search/', Search2ResultForm.as_view(), name='search2'),
	url(r'^contact/', contact.as_view(), name='contact'),
	url(r'^Analyst/', include('Analyst.urls', namespace="Analyst")),
	url(r'^Disclosure/', include('Disclosure.urls', namespace="Disclosure")),
	url(r'^Issue/', include('Issue.urls', namespace="Issue")),
	url(r'^factbook/', include('factbook.urls', namespace="factbook")),
	url(r'^IRLink/', include('IRLink.urls', namespace="IRLink")),
	url(r'^ckeditor/', include('ckeditor_uploader.urls')),
	
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root =settings.STATIC_ROOT)

if settings.DEBUG:
	urlpatterns += [
	   url(r'media/(?P<path>.*)$',
             serve, {
                 'document_root' : settings.MEDIA_ROOT,
            }
        ),          
]

#정규표현식에 따라서 홈페이지의 url을 만들어 줍니다.

factbook/models.py
from __future__ import unicode_literals
from ckeditor.fields import RichTextField #text를 자유자재로 수정하기 위한 tool 사용
from ckeditor_uploader.fields import RichTextUploadingField #text를 자유자재로 수정하기 위한 tool 사용
from django.db import models
from django.utils import timezone #현재 시간을 가져오기 위한 도구
from Info.models import * #타 model import
from django.contrib.auth.models import User #model에서 User를 사용하기 위한 도구


class Post(models.Model):
	company = models.ForeignKey(company_name) #회사 이름
	CATE_CHOICES = (
		('Corporate Overview', (
				('business scope', 'Business Scope'),
				('history', 'History'),
				('change in capital', 'Change in Capital'),
				('share with voting right', 'Share with Voting Right'),
				('dividend', 'Dividend'),
			)
		),
		('Business and Operation', (
					('industry overview', 'Industry Overview'),
					('performance by segment', 'Performance by segment'),
					('cost of product', 'Cost of Product'),
					('average sell price', 'Average Sell Price'),
					('production and utilization', 'Production and Utilization'),
			)
		),
		('Risk Analysis', (
				('liquidity risk', 'Liquidity Risk'),
				('f/x exposure', 'F/X Exposure'),
				('interest risk', 'Interest Risk'),
				('credit risk', 'Credit Risk'),
				('other risk', 'Other Risk'),
			)
		),
		('Financials', (
			('income statement', 'Income Statement'),
			('balance sheet', 'Balance Sheet'),
			('cash flow', 'Cash Flow'),
			)
		),
		('Governance', (
			('ownership', 'Ownership'),
			('bod/management', 'BOD/Management'),
			('management', 'Management'),
			)
		),
		('Affiliates', (
			('affiliates', 'Affiliates'),
			)
		),
		('Investment', (
			('investment', 'Investment'),
			)
		),
	) #이미 있는 카테고리를 계층화하여 선택할 수 있게 만들었습니다.
	category = models.CharField(max_length = 30, choices=CATE_CHOICES,default='business scope') #앞서 만들었던 카테고리를 선택할 수 있게 하는 field입니다.
	text = RichTextUploadingField() #내용
	created_date = models.DateTimeField(default=timezone.now) #글의 생성일자
	published_date = models.DateTimeField(blank=True, null=True) #글의 게시일자

	def publish(self):
		self.published_date = timezone.now() #현재 일시 사용
		self.save()

class factbook_document(models.Model):
	company = models.ForeignKey(company_name) #회사 이름
	fact_document = models.FileField(null = True) #문서 업로드
	location = models.CharField(max_length = 250) #문서이름
	price = models.DecimalField(decimal_places = 2, max_digits=7) #문서에 대한 가격

class factbook_Purchase(models.Model): #paypal에서 제공된 코드
	resource = models.ForeignKey(factbook_document)
	purchaser = models.ForeignKey(User)
	purchased_at = models.DateTimeField(auto_now_add=True)
	tx = models.CharField(max_length=250)

factbook/forms.py
from django import forms

class PostSearchForm(forms.Form):
	search_word = forms.CharField(
		max_length=100,
		widget=forms.TextInput(
			attrs={
				'placeholder' : '  Type In Company Name or Ticker',
				'required': 'True',
			}
		)
	)
#검색을 위한 Form - 검색어를 입력받는 공간에 대한 정의
#placeholder - 배경에 글씨를 띄웁니다.
#required:True - 빈 칸을 허용하지 않습니다.

class fact_busi(forms.Form):
	search = forms.CharField(max_length=100)

class fact_hist(forms.Form):
	search = forms.CharField(max_length=100)

class fact_capi(forms.Form):
	search = forms.CharField(max_length=100)

class fact_righ(forms.Form):
	search = forms.CharField(max_length=100)

class fact_divi(forms.Form):
	search = forms.CharField(max_length=100)

class fact_liqu(forms.Form):
	search = forms.CharField(max_length=100)

class fact_expo(forms.Form):
	search = forms.CharField(max_length=100)

class fact_inte(forms.Form):
	search = forms.CharField(max_length=100)

class fact_cred(forms.Form):
	search = forms.CharField(max_length=100)

class fact_owne(forms.Form):
	search = forms.CharField(max_length=100)

class fact_bod(forms.Form):
	search = forms.CharField(max_length=100)

class fact_mana(forms.Form):
	search = forms.CharField(max_length=100)

class fact_indu(forms.Form):
	search = forms.CharField(max_length=100)

class fact_perf(forms.Form):
	search = forms.CharField(max_length=100)

class fact_cost(forms.Form):
	search = forms.CharField(max_length=100)

class fact_aver(forms.Form):
	search = forms.CharField(max_length=100)

class fact_prod(forms.Form):
	search = forms.CharField(max_length=100)

class fact_inco(forms.Form):
	search = forms.CharField(max_length=100)

class fact_bala(forms.Form):
	search = forms.CharField(max_length=100)

class fact_cash(forms.Form):
	search = forms.CharField(max_length=100)

class fact_othe(forms.Form):
	search = forms.CharField(max_length=100)

class fact_affi(forms.Form):
	search = forms.CharField(max_length=100)

class fact_inve(forms.Form):
	search = forms.CharField(max_length=100)

#Factbook의 항목들을 Form으로 제작하여 필요한 정보를 담았습니다.
#필요한 정보는 현재 회사 정보를 가지고 있습니다.

factbook/templates/factbook/down.html
<head>
	<title>down.html</title>
	{% load staticfiles %}
	<link rel = "stylesheet" type="text/css" href={% static "css/down.css" %} />

</head>
		
<div id = "wrap">
	<div id = "box">
		<div id = "Avail_Resource">		
			<p>Available Resources</p>
		</div>
		<div id = "item_list">
			<ul>
			{% for item in list %}
			<li><a href="{% url 'item' item.id %}">{{ item.company.title }} - ${{ item.price|floatformat:2 }}</a></li>
			{% endfor %}
			</ul>
		</div>
		<div id = "your_prof">
			<a href="/accounts/profile">Your profile</a>
		</div>
</div>

factbook/templates/factbook/down_sam.html
<head>
	<title>down_sam.html</title>
	{% load staticfiles %}
	<link rel = "stylesheet" type="text/css" href={% static "css/down.css" %} />

</head>
		
<div id = "wrap">
	<div id = "box">
		<div id = "Avail_Resource">		
			<p>Available Resources</p>
		</div>
		<div id = "item_list">
			<ul>
			{% for item in list %}
			<li><a href="{% url 'factbook:item' item.id %}">{{ item.company.title }} - ${{ item.price|floatformat:2 }}</a></li>
			{% endfor %}
			</ul>
		</div>
		<div id = "your_prof">
			<a href="/accounts/profile">Your profile</a>
		</div>
</div>

factbook/templates/factbook/factbook.html
{% extends "base.html" %}

{% block title %}factbook.html{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "css/factbook.css" %}{% endblock %}

{% block content %}

		<form id="searchbox" action="{% url 'search2' %}" method="post"> {% csrf_token %}
		
				{{form.search_word}}
			
			<input id="submit" type="image" src="{% static "photo/search.png" %}">
		</form>
	
	<div id="wrap">
		<div id="box">
			<div id="aside">
				<nav id="asideMenu" >
					<ul> 
						<li><a class="menuLink"  href="{% url 'factbook:factbook_list' %}">Factbook</a></li> 
						<li><a class="menuLink"  href="{% url 'Disclosure:disclosure_samsung' %}">Disclosures</a></li> 
						<li><a class="menuLink"  href="{% url 'Analyst:Analyst_samsung' %}">Analyst Report</a></li> 
						<li><a class="menuLink" href="{% url 'Issue:Industry_Analysis_samsung' %}">Industry Info</a></li> 
						<li><a class="menuLink" href="{% url 'IRLink:IRLink_home' %}">IR Link</a></li>

					</ul> 
				</nav>
			</div>
			<!---                            룰루랄라     게시판 부분(목록)                                  -->
			<div id="all_section">
				<div id=date>
					<b class="date_font">Factbook</b>
					<!--<a href=""><b class="date_font"><</b></a>
					 날짜 바뀔
					<a href=""><b class="date_font">></b></a> -->
				</div>
				<div id="company_info">
					<h2 id=name>Samsung Electronics</h2> 
					<h3 id=num>KS005930</h3>
				</div>
				
				<div id="Corporate_Overview" class="section">
					<a class="menu_title">Corporate Overview</a>

					<table class="subtitle">
						<tbody><!-- 게시판 하나하나 -->
							<form id="business_scope" action="{% url 'factbook:factbook_detail' %}" target="_blank" method="post"> {% csrf_token %}
								<input type="hidden" name="search" value="Samsung Electronics">
								<input id="business" type="submit" value="Business Scope" name = fac_bus>
							</form>
							
							<form id="fac_history" action="{% url 'factbook:factbook_detail' %}" target="_blank"  method="post"> {% csrf_token %}
								<input type="hidden" name="search" value="Samsung Electronics">
								<input id="history" type="submit" value="History" name = fac_his>
							</form>

							<form id="Change_in_Capital" action="{% url 'factbook:factbook_detail' %}" target="_blank"  method="post"> {% csrf_token %}
								<input type="hidden" name="search" value="Samsung Electronics"}>
								<input id="capital" type="submit" value="Change in Capital" name = fac_cap>
							</form>

							<form id="Share_with_Voting_Right" action="{% url 'factbook:factbook_detail' %}" target="_blank"  method="post"> {% csrf_token %}
								<input type="hidden" name="search" value="Samsung Electronics">
								<input id="right" type="submit" value="Share with Voting Right" name = fac_rig>
							</form>

							<form id="fac_Dividend" action="{% url 'factbook:factbook_detail' %}" target="_blank"  method="post"> {% csrf_token %}
								<input type="hidden" name="search" value="Samsung Electronics">
								<input id="Dividend" type="submit" value="Dividend" name = fac_div>
							</form>	
						</tbody>
					</table>
				</div>

				<div id="Risk_Analysis" class="section">
					<a class="menu_title">Risk Analysis</a>

					<table class="subtitle">
						<tbody>
							<form id="liquidity_risk" action="{% url 'factbook:factbook_detail' %}" target="_blank"  method="post"> {% csrf_token %}
								<input type="hidden" name="search" value="Samsung Electronics">
								<input id="liquidity" type="submit" value="Liquidity Risk" name = fac_liq>
							</form>	
							
							<form id="fx_exposure" action="{% url 'factbook:factbook_detail' %}" target="_blank"  method="post"> {% csrf_token %}
								<input type="hidden" name="search" value="Samsung Electronics">
								<input id="fx" type="submit" value="F/X Exposure" name = fac_fx>
							</form>	
							
							<form id="interest_risk" action="{% url 'factbook:factbook_detail' %}" target="_blank"  method="post"> {% csrf_token %}
								<input type="hidden" name="search" value="Samsung Electronics">
								<input id="interest" type="submit" value="Interest Risk" name = fac_int>
							</form>	
							
							<form id="credit_risk" action="{% url 'factbook:factbook_detail' %}" target="_blank"  method="post"> {% csrf_token %}
								<input type="hidden" name="search" value="Samsung Electronics">
								<input id="credit" type="submit" value="Credit Risk" name = fac_cre>
							</form>	

							<form id="other_risk" action="{% url 'factbook:factbook_detail' %}" target="_blank"  method="post"> {% csrf_token %}
								<input type="hidden" name="search" value="Samsung Electronics">
								<input id="other_r" type="submit" value="Other Risk" name = fac_oth>
							</form>
						</tbody>
					</table>
				</div>

				<div id="Governance" class="section">
					<a class="menu_title">Governance</a>

					<table class="subtitle">
						<tbody>
							<form id="fact_ownership" action="{% url 'factbook:factbook_detail' %}" target="_blank"  method="post"> {% csrf_token %}
								<input type="hidden" name="search" value="Samsung Electronics">
								<input id="ownership" type="submit" value="Ownership" name = fac_own>
							</form>	
							
							<form id="bod_management" action="{% url 'factbook:factbook_detail' %}" target="_blank"  method="post"> {% csrf_token %}
								<input type="hidden" name="search" value="Samsung Electronics">
								<input id="bod" type="submit" value="BOD/Management" name = fac_bod>
							</form>	
							
							<form id="fact_management" action="{% url 'factbook:factbook_detail' %}" target="_blank"  method="post"> {% csrf_token %}
								<input type="hidden" name="search" value="Samsung Electronics">
								<input id="management" type="submit" value="Management" name = fac_man>
							</form>	
						</tbody>
					</table>
				</div>

				<div id="Businness_and_Operation" class="section">
					<a class="menu_title">Business and Operation</a>

					<table class="subtitle">
						<tbody><!-- 게시판 하나하나 -->
							<form id="industry_overview" action="{% url 'factbook:factbook_detail' %}" target="_blank"  method="post"> {% csrf_token %}
								<input type="hidden" name="search" value="Samsung Electronics">
								<input id="industry" type="submit" value="Industry Overview" name = fac_ind>
							</form>	
							
							<form id="performance_by_segment" action="{% url 'factbook:factbook_detail' %}" target="_blank"  method="post"> {% csrf_token %}
								<input type="hidden" name="search" value="Samsung Electronics">
								<input id="performance" type="submit" value="Performance by segment" name = fac_per>
							</form>	
							
							<form id="cost_of_product" action="{% url 'factbook:factbook_detail' %}" target="_blank"  method="post"> {% csrf_token %}
								<input type="hidden" name="search" value="Samsung Electronics">
								<input id="cost" type="submit" value="Cost of Product" name = fac_cos>
							</form>	

							<form id="average_sell_price" action="{% url 'factbook:factbook_detail' %}" target="_blank"  method="post"> {% csrf_token %}
								<input type="hidden" name="search" value="Samsung Electronics">
								<input id="average" type="submit" value="Average Selling Price" name = fac_ave>
							</form>	

							<form id="production_and_utilization" action="{% url 'factbook:factbook_detail' %}" target="_blank"  method="post"> {% csrf_token %}
								<input type="hidden" name="search" value="Samsung Electronics">
								<input id="production" type="submit" value="Production and Utilization" name = fac_pro>
							</form>	
						</tbody>
					</table>
				</div>

				<div id="Financials" class="section">
					<a class="menu_title">Financials</a>

					<table class="subtitle">
						<tbody><!-- 게시판 하나하나 -->
							<form id="income_statement" action="{% url 'factbook:factbook_detail' %}" target="_blank"  method="post"> {% csrf_token %}
								<input type="hidden" name="search" value="Samsung Electronics">
								<input id="income" type="submit" value="Income Statement" name = fac_inc>
							</form>
							
							<form id="balance_sheet" action="{% url 'factbook:factbook_detail' %}" target="_blank"  method="post"> {% csrf_token %}
								<input type="hidden" name="search" value="Samsung Electronics">
								<input id="balance" type="submit" value="Balance Sheet" name = fac_bal>
							</form>
							
							<form id="cash_flow" action="{% url 'factbook:factbook_detail' %}" target="_blank"  method="post"> {% csrf_token %}
								<input type="hidden" name="search" value="Samsung Electronics">
								<input id="cash" type="submit" value="Cash Flow" name = fac_cas>
							</form>
						</tbody>
					</table>
				</div>

				<form id="Affiliates" action="{% url 'factbook:factbook_detail' %}" target="_blank" method="post"> {% csrf_token %}
					<input type="hidden" name="search" value="Samsung Electronics">
					<input id="affi" type="submit" value="Affiliates" name = fac_aff>
				</form>

				<form id="Other_Investment" action="{% url 'factbook:factbook_detail' %}" target="_blank" method="post"> {% csrf_token %}
					<input type="hidden" name="search" value="Samsung Electronics">
					<input id="inve" type="submit" value="Investment" name = fac_inv>
				</form>

				<a href="{% url 'factbook:down_sam' %} " target="_blank"><img id="pdf_logo" src="{% static "photo/pdf_icon.png" %}"></a>
				<!---                             게시판 부분(목록)                     룰루룰랄라                -->
			</div>
		</div>
	</div>
{% endblock content %}


factbook/templates/factbook/purchase.html
<html>
<body>
<p>Purchase <b>{{ resource.company.title }}</b> for <b>${{ resource.price|floatformat:2 }}</b></p>
<p>
<form action="{{ paypal_url }}" method="post">
  <input type="hidden" name="amount" value="{{ resource.price }}">
  <input type="hidden" name="cmd" value="_xclick">
  <input type="hidden" name="business" value="{{ paypal_email }}">
  <input type="hidden" name="item_name" value="{{ resource.name }}">
  <input type="hidden" name="currency_code" value="USD">
  <input type="hidden" name="return" value="{{ paypal_return_url }}/factbook/purchased/{{ user.id }}/{{resource.id}}">
  <input type="hidden" name="cancel_return" value="{{ paypal_return_url }}/">
  <input type="image" src="http://www.paypal.com/en_AU/i/btn/x-click-but01.gif" name="submit" alt="Make payments with PayPal - it's fast, free and secure!">
</form>
</p>
</body>
</html>

factbook/templates/factbook/purchased.html
<html>
<body>
<p>You have successfully purchased <b>{{ resource.company.title }}</b></p>
<p><a href="/factbook/download/{{ resource.id }}/">Download Now</a></p>
</body>
</html>